# File: config.yaml
# FE-AI System Configuration

# Application Settings
app:
  name: "FE-AI Gait Disease Detection"
  version: "2.3.1"
  environment: "production"  # development, staging, production
  debug: false
  secret_key: "fe-ai-secure-key-change-in-production"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8501
  max_upload_size: 100  # MB
  session_timeout: 7200  # seconds
  enable_cors: true
  ssl_enabled: false
  ssl_cert_path: "/certs/cert.pem"
  ssl_key_path: "/certs/key.pem"

# Model Configuration
models:
  gait_detector:
    architecture: "CNN-BiLSTM"
    confidence_threshold: 0.8
    sequence_length: 250
    input_dim: 6
    cnn_filters: 64
    lstm_units: 128
    dropout_rate: 0.3
    model_path: "data/models/gait_detector_v2.1.pth"
    
  disease_classifier:
    transformer:
      input_dim: 247
      d_model: 512
      nhead: 8
      num_layers: 6
      dim_feedforward: 2048
      dropout: 0.1
      num_classes: 5
      max_len: 100
    xgboost:
      n_estimators: 1000
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      reg_alpha: 0.1
      reg_lambda: 1.0
      random_state: 42
    ensemble_weight: 0.7  # Transformer weight in ensemble
    model_path: "data/models/disease_classifier_v2.1.pkl"

# Federated Learning Configuration
federated_learning:
  enabled: true
  server_address: "0.0.0.0:8080"
  num_rounds: 50
  min_fit_clients: 3
  min_evaluate_clients: 2
  min_available_clients: 3
  epochs_per_round: 5
  batch_size: 32
  learning_rate: 0.001
  privacy_budget: 1.0
  aggregation_method: "FedAvg"  # FedAvg, FedProx, FedOpt
  
  # Privacy Settings
  differential_privacy:
    enabled: true
    epsilon: 1.0
    delta: 1e-5
    max_grad_norm: 1.0
    
  secure_aggregation:
    enabled: true
    encryption_method: "AES256"
    key_rotation_rounds: 10

# Data Processing Configuration
preprocessing:
  sampling_rate: 50  # Hz
  window_size: 5  # seconds
  overlap_percentage: 25
  normalization_method: "zscore"  # zscore, minmax, robust
  
  filters:
    lowpass_freq: 20  # Hz
    highpass_freq: 0.5  # Hz
    filter_order: 4
    filter_type: "butterworth"
    
  feature_extraction:
    time_domain: true
    frequency_domain: true
    wavelet_domain: true
    statistical_features: true

# Database Configuration
database:
  type: "mongodb"  # mongodb, postgresql, sqlite
  mongodb:
    host: "localhost"
    port: 27017
    database: "fe_ai_system"
    username: null
    password: null
    auth_database: "admin"
    ssl_enabled: false
    replica_set: null
    
  collections:
    analyses: "analyses"
    users: "users" 
    models: "models"
    logs: "system_logs"
    feedback: "clinical_feedback"

# Security Configuration
security:
  authentication:
    enabled: true
    method: "local"  # local, ldap, oauth2
    session_duration: 7200  # seconds
    max_login_attempts: 5
    lockout_duration: 300  # seconds
    
  authorization:
    rbac_enabled: true
    default_role: "viewer"
    roles:
      admin: ["read", "write", "delete", "manage_users", "system_config"]
      doctor: ["read", "write", "analyze", "export_reports"]
      researcher: ["read", "analyze", "export_data"]
      viewer: ["read"]
      
  encryption:
    data_at_rest: true
    data_in_transit: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
  audit:
    enabled: true
    log_all_actions: true
    retention_days: 365
    export_format: "json"

# Logging Configuration  
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      
    file:
      enabled: true
      level: "DEBUG"
      path: "logs/"
      max_size: "100MB"
      backup_count: 5
      
    syslog:
      enabled: false
      host: "localhost"
      port: 514
      
  loggers:
    fe_ai:
      level: "DEBUG"
    federated:
      level: "INFO"
    security:
      level: "WARNING"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_collection: true
  health_check_interval: 30  # seconds
  
  alerts:
    enabled: true
    email_notifications: true
    slack_notifications: false
    
  thresholds:
    cpu_usage: 80  # percentage
    memory_usage: 85  # percentage
    disk_usage: 90  # percentage
    response_time: 5000  # milliseconds
    error_rate: 5  # percentage

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM (cron format)
  retention_days: 30
  compression: true
  encryption: true
  
  targets:
    database: true
    models: true
    logs: false
    configurations: true
    
  storage:
    type: "local"  # local, s3, azure, gcp
    path: "backups/"

# Cache Configuration
cache:
  enabled: true
  type: "redis"  # redis, memcached, memory
  
  redis:
    host: "localhost"
    port: 6379
    database: 0
    password: null
    ssl_enabled: false
    
  ttl:
    analysis_results: 3600  # seconds
    user_sessions: 7200  # seconds
    model_predictions: 1800  # seconds

# API Configuration
api:
  enabled: true
  version: "v1"
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst_size: 10
    
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["*"]
    
  authentication:
    api_keys: true
    jwt_tokens: true
    oauth2: false

# Email Configuration
email:
  enabled: true
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: null
  password: null
  use_tls: true
  from_address: "noreply@fe-ai-system.com"
  
  templates:
    welcome: "templates/welcome.html"
    alert: "templates/alert.html"
    report: "templates/report.html"

# External Services
external_services:
  mlflow:
    enabled: false
    tracking_uri: "http://localhost:5000"
    
  wandb:
    enabled: false
    project: "fe-ai-gait-detection"
    
  sentry:
    enabled: false
    dsn: null

# Development Settings
development:
  auto_reload: true
  debug_mode: true
  mock_data: false
  skip_auth: false
  profiling: false